apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebapp
          image: prasad522/mavenwebapp:4
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: javawebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: javawebapp
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mavenwebapp-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 95
