apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  namespace: test-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - name: nodejsapp
          image: prasad522/nodejsapp:1
          ports:
            - containerPort: 9981
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-nodeport-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
    - port: 9981
      targetPort: 9981
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejsapp
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejsapp
    namespace: test-ns
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 95
