apiVersion: v1
kind: Pod
metadata:
  name: mavenwebapppod
  labels:
    app: mavenwebapp
    team: developer
    manager: Ravindra
  namespace: test-ns
spec:
  containers:
    - name: mavenwebappcontainer
      image: prasad522/mavenwebapp:1
      # Here we didnt define any resources requests and limits
      # when you create LimitRanges K8s will automatically enforce these resources automatically to every container. 
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappnodeport
  namespace: test-ns
spec:
  type: NodePort 
  selector: 
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
    