apiVersion: v1
kind: Nmaespace
metadata:
  name: test-ns
  labels:
    team: testing
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota
  namespace: test-ns
spec:
    hard:
	  pods: "3"
	  count/deployments.apps: "2"
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "2"
      limits.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 300m
	  memory: 300Mi
    defaultRequest: # this section defines default requests
      cpu: 600m
	  memory: 600Mi
    type: Container