apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongonfspvc
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 1Gi
  volumeName: mongonfsvol