apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongonfsvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.25 #nfs-Server privateip address
    path: /mnt/nfs-share