apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbotapp
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp  # Corrected indentation
    spec:
      containers:
        - name: springbootapp
          image: prasad522/springbootapp:1
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOSTNAME
              value: mongoheadlesssvc
            - name: MONGODB_USERNAME
              value: devdb
            - name: MONGODB_PASSWORD
              value: devdb123@
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: springbootappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: springbootapp
  ports:
    - port: 80
      targetPort: 8080
