apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      volumes:
        - name: configvol
          configMap:
            name: mavenwebappconfig
            items:
               - key: tomcat-users.xml
                 path: tomcat-users.xml
      containers:
        - name: mavenwebapp
          image: prasad522/mavenwebapp:4
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: configvol
              mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
              subPath: "tomcat-users.xml"        
---
apiVersion: v1
kind: Service 
metadata:
  name: mavenwebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
