apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebapp
          image: prasad522/mavenwebapp:4
          ports:
            - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service 
metadata:
  name: javawebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
