apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      namespace: test-ns
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongonfsvol
          persistentVolumeClaim:
            claimName: mongonfspvc
      containers:
        - name: mongo
          image: mongo:4.4.23-focal
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: devdb
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: dev123@
          volumeMounts:
            - name: mongonfsvol
              mountPath: /data/db/
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongonfspvc
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 1Gi
  volumeName: mongonfsvol
