apiVersion: v1
kind: Pod
metadata:
  name: mavenwebapppod
  labels:
    app: mavenwebapp
    team: developer
    manager: Ravindra
  namespace: test-ns
spec:
  containers:
    - name: mavenwebappcontainer
      image: prasad522/mavenwebapp:1
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "0.5"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: test-ns
spec:
  type: ClusterIP
  selectors: 
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080