apiVersion: v1
kind: Pod
metadata:
  name: mavenwebapppod
  labels:
    app: mavenwebapp
    team: developer
    manager: Ravindra
  namespace: test-ns
spec:
  containers:
    - name: mavenwebappcontainer
      image: prasad522/mavenwebapp:1
      ports:
        - containerPort: 8080