apiVersion: v1
kind: Pod
metadata:
  name: nodejs_nginxPod
  labels:
    app: nodejs_nginxApp
    team: developer
    manager: Srinu
  namespace: test-ns
spec:
  containers:
    - name: nodejsappcontainer
      image: prasad522/nodejsapp:1
      ports:
        - containerPort: 9981
    - name: nginxContainer
      image: nginx
      ports:
        - containerPort: 80
