apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: javawebapprc
  namespace: test-ns
spec:
  #replicas: 2
  selectors:
    matchLabels:
      app: javawebapp 
  template:
    metadata:
      name: javawebapp
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebapp
          image: prasad522/javawebapp:1
          ports:
            - containerPort: 8080
---