apiVersion: v1
kind: ReplicationController
metadata: 
  name: mavenwebapprc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template: 
    metadata:
      name: mavenwebapp
      labels: 
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebapp
          image: prasad522/mavenwebapp:4
          ports:
            - containerPort: 8080
---