apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejsapp-rs
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - name: nodejsapp
          image: prasad522/nodejsapp:1
          ports:
            - containerPort: 9981
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
